# ClusterLogSink configure fluentbit to send logs to Syslog Receiver
apiVersion: pksapi.io/v1beta1
kind: ClusterLogSink
metadata:
   name: workload-sink
spec:
   type: syslog
   # Using syslog/incluster Service
   host: otelcol-syslog-incluster-svc.default
   port: 6514
   # non-tls endpoint is forbiden
   enable_tls: true
   insecure_skip_verify: true
