# ClusterLogSink configure fluentbit to send logs to Syslog Receiver
apiVersion: pksapi.io/v1beta1
kind: ClusterLogSink
metadata:
   name: workload-sink
spec:
   type: syslog
   # Using NodePort
   host: 10.198.13.4
   port: 30414
   # non-tls endpoint is forbiden
   enable_tls: true
   insecure_skip_verify: true

